name: Run tests

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: palumba
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: testing
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, pdo_pgsql, zip
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Set up .env file
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Run artisan test
        run: php artisan test

      - name: Run pint
        run: php ./vendor/bin/pint --test
